version: '3.8'

services:
  backend:
    build: ./backend
    container_name: prestasi-siswa-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/prestasi_siswa
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - prestasi-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: prestasi-siswa-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - prestasi-network

  db:
    image: postgres:13
    container_name: prestasi-siswa-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prestasi_siswa
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - prestasi-network

networks:
  prestasi-network:
    driver: bridge

volumes:
  pgdata: